version: "3"
services:

    client-behavior-emulator:
        image: client-behavior-emulator
        build:
            context: .
            dockerfile: ./ClientBehaviorEmulator/Dockerfile
        depends_on:
            - rabbitmq

    order-service:
        image: order-service
        build:
            context: .
            dockerfile: ./OrderService/Dockerfile
        depends_on:
            - rabbitmq

    shipping-service:
        image: shipping-service
        build:
            context: .
            dockerfile: ./ShippingService/Dockerfile
        depends_on:
            - rabbitmq
              
    billing-service:
        image: billing-service
        build:
            context: .
            dockerfile: ./BillingService/Dockerfile
        depends_on:
            - rabbitmq
                
                
    
    rabbitmq:
        image: rabbitmq-cluster
        hostname: rabbitmq
        environment:
            - ERLANG_COOKIE=abcdefg
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - "15672:15672"
            - "5672:5672"